version: "3.7"

services:
  starter:
    image: dadarek/wait-for-dependencies:latest
    command: nginx:80 postgres:5432
    depends_on:
      - nginx
      - postgres

  nginx:
    image: nginx:1.19-alpine
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./resources/nginx/devel_vhost.conf:/etc/nginx/conf.d/default.conf
      - ./wwwroot:/var/www/erlcing.devel/wwwroot

  postgres:
    image: 1maa/postgres:12-alpine
    environment:
      - POSTGRES_DB=erlcing_devel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:2345:5432"
    volumes:
      - ./resources/postgres/schema.sql:/tmp/schema.sql
